# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/sm64tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/sm64tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/sm64tools/CMakeFiles /mnt/d/sm64tools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/sm64tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named n64cksum

# Build rule for target.
n64cksum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n64cksum
.PHONY : n64cksum

# fast build rule for target.
n64cksum/fast:
	$(MAKE) -f CMakeFiles/n64cksum.dir/build.make CMakeFiles/n64cksum.dir/build
.PHONY : n64cksum/fast

#=============================================================================
# Target rules for targets named n64split

# Build rule for target.
n64split: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n64split
.PHONY : n64split

# fast build rule for target.
n64split/fast:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/build
.PHONY : n64split/fast

#=============================================================================
# Target rules for targets named mipsdisasm

# Build rule for target.
mipsdisasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mipsdisasm
.PHONY : mipsdisasm

# fast build rule for target.
mipsdisasm/fast:
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/build
.PHONY : mipsdisasm/fast

#=============================================================================
# Target rules for targets named mio0

# Build rule for target.
mio0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mio0
.PHONY : mio0

# fast build rule for target.
mio0/fast:
	$(MAKE) -f CMakeFiles/mio0.dir/build.make CMakeFiles/mio0.dir/build
.PHONY : mio0/fast

#=============================================================================
# Target rules for targets named sm64extend

# Build rule for target.
sm64extend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm64extend
.PHONY : sm64extend

# fast build rule for target.
sm64extend/fast:
	$(MAKE) -f CMakeFiles/sm64extend.dir/build.make CMakeFiles/sm64extend.dir/build
.PHONY : sm64extend/fast

#=============================================================================
# Target rules for targets named sm64

# Build rule for target.
sm64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm64
.PHONY : sm64

# fast build rule for target.
sm64/fast:
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/build
.PHONY : sm64/fast

#=============================================================================
# Target rules for targets named sm64walk

# Build rule for target.
sm64walk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm64walk
.PHONY : sm64walk

# fast build rule for target.
sm64walk/fast:
	$(MAKE) -f CMakeFiles/sm64walk.dir/build.make CMakeFiles/sm64walk.dir/build
.PHONY : sm64walk/fast

#=============================================================================
# Target rules for targets named f3d

# Build rule for target.
f3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 f3d
.PHONY : f3d

# fast build rule for target.
f3d/fast:
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/build
.PHONY : f3d/fast

#=============================================================================
# Target rules for targets named sm64compress

# Build rule for target.
sm64compress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm64compress
.PHONY : sm64compress

# fast build rule for target.
sm64compress/fast:
	$(MAKE) -f CMakeFiles/sm64compress.dir/build.make CMakeFiles/sm64compress.dir/build
.PHONY : sm64compress/fast

#=============================================================================
# Target rules for targets named sm64geo

# Build rule for target.
sm64geo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm64geo
.PHONY : sm64geo

# fast build rule for target.
sm64geo/fast:
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/build
.PHONY : sm64geo/fast

blast.o: blast.c.o

.PHONY : blast.o

# target to build an object file
blast.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/blast.c.o
.PHONY : blast.c.o

blast.i: blast.c.i

.PHONY : blast.i

# target to preprocess a source file
blast.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/blast.c.i
.PHONY : blast.c.i

blast.s: blast.c.s

.PHONY : blast.s

# target to generate assembly for a file
blast.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/blast.c.s
.PHONY : blast.c.s

f3d.o: f3d.c.o

.PHONY : f3d.o

# target to build an object file
f3d.c.o:
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/f3d.c.o
.PHONY : f3d.c.o

f3d.i: f3d.c.i

.PHONY : f3d.i

# target to preprocess a source file
f3d.c.i:
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/f3d.c.i
.PHONY : f3d.c.i

f3d.s: f3d.c.s

.PHONY : f3d.s

# target to generate assembly for a file
f3d.c.s:
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/f3d.c.s
.PHONY : f3d.c.s

libmio0.o: libmio0.c.o

.PHONY : libmio0.o

# target to build an object file
libmio0.c.o:
	$(MAKE) -f CMakeFiles/mio0.dir/build.make CMakeFiles/mio0.dir/libmio0.c.o
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libmio0.c.o
.PHONY : libmio0.c.o

libmio0.i: libmio0.c.i

.PHONY : libmio0.i

# target to preprocess a source file
libmio0.c.i:
	$(MAKE) -f CMakeFiles/mio0.dir/build.make CMakeFiles/mio0.dir/libmio0.c.i
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libmio0.c.i
.PHONY : libmio0.c.i

libmio0.s: libmio0.c.s

.PHONY : libmio0.s

# target to generate assembly for a file
libmio0.c.s:
	$(MAKE) -f CMakeFiles/mio0.dir/build.make CMakeFiles/mio0.dir/libmio0.c.s
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libmio0.c.s
.PHONY : libmio0.c.s

libsfx.o: libsfx.c.o

.PHONY : libsfx.o

# target to build an object file
libsfx.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/libsfx.c.o
.PHONY : libsfx.c.o

libsfx.i: libsfx.c.i

.PHONY : libsfx.i

# target to preprocess a source file
libsfx.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/libsfx.c.i
.PHONY : libsfx.c.i

libsfx.s: libsfx.c.s

.PHONY : libsfx.s

# target to generate assembly for a file
libsfx.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/libsfx.c.s
.PHONY : libsfx.c.s

libsm64.o: libsm64.c.o

.PHONY : libsm64.o

# target to build an object file
libsm64.c.o:
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libsm64.c.o
.PHONY : libsm64.c.o

libsm64.i: libsm64.c.i

.PHONY : libsm64.i

# target to preprocess a source file
libsm64.c.i:
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libsm64.c.i
.PHONY : libsm64.c.i

libsm64.s: libsm64.c.s

.PHONY : libsm64.s

# target to generate assembly for a file
libsm64.c.s:
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/libsm64.c.s
.PHONY : libsm64.c.s

mipsdisasm.o: mipsdisasm.c.o

.PHONY : mipsdisasm.o

# target to build an object file
mipsdisasm.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/mipsdisasm.c.o
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/mipsdisasm.c.o
.PHONY : mipsdisasm.c.o

mipsdisasm.i: mipsdisasm.c.i

.PHONY : mipsdisasm.i

# target to preprocess a source file
mipsdisasm.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/mipsdisasm.c.i
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/mipsdisasm.c.i
.PHONY : mipsdisasm.c.i

mipsdisasm.s: mipsdisasm.c.s

.PHONY : mipsdisasm.s

# target to generate assembly for a file
mipsdisasm.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/mipsdisasm.c.s
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/mipsdisasm.c.s
.PHONY : mipsdisasm.c.s

n64cksum.o: n64cksum.c.o

.PHONY : n64cksum.o

# target to build an object file
n64cksum.c.o:
	$(MAKE) -f CMakeFiles/n64cksum.dir/build.make CMakeFiles/n64cksum.dir/n64cksum.c.o
.PHONY : n64cksum.c.o

n64cksum.i: n64cksum.c.i

.PHONY : n64cksum.i

# target to preprocess a source file
n64cksum.c.i:
	$(MAKE) -f CMakeFiles/n64cksum.dir/build.make CMakeFiles/n64cksum.dir/n64cksum.c.i
.PHONY : n64cksum.c.i

n64cksum.s: n64cksum.c.s

.PHONY : n64cksum.s

# target to generate assembly for a file
n64cksum.c.s:
	$(MAKE) -f CMakeFiles/n64cksum.dir/build.make CMakeFiles/n64cksum.dir/n64cksum.c.s
.PHONY : n64cksum.c.s

n64split.o: n64split.c.o

.PHONY : n64split.o

# target to build an object file
n64split.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/n64split.c.o
.PHONY : n64split.c.o

n64split.i: n64split.c.i

.PHONY : n64split.i

# target to preprocess a source file
n64split.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/n64split.c.i
.PHONY : n64split.c.i

n64split.s: n64split.c.s

.PHONY : n64split.s

# target to generate assembly for a file
n64split.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/n64split.c.s
.PHONY : n64split.c.s

sm64compress.o: sm64compress.c.o

.PHONY : sm64compress.o

# target to build an object file
sm64compress.c.o:
	$(MAKE) -f CMakeFiles/sm64compress.dir/build.make CMakeFiles/sm64compress.dir/sm64compress.c.o
.PHONY : sm64compress.c.o

sm64compress.i: sm64compress.c.i

.PHONY : sm64compress.i

# target to preprocess a source file
sm64compress.c.i:
	$(MAKE) -f CMakeFiles/sm64compress.dir/build.make CMakeFiles/sm64compress.dir/sm64compress.c.i
.PHONY : sm64compress.c.i

sm64compress.s: sm64compress.c.s

.PHONY : sm64compress.s

# target to generate assembly for a file
sm64compress.c.s:
	$(MAKE) -f CMakeFiles/sm64compress.dir/build.make CMakeFiles/sm64compress.dir/sm64compress.c.s
.PHONY : sm64compress.c.s

sm64extend.o: sm64extend.c.o

.PHONY : sm64extend.o

# target to build an object file
sm64extend.c.o:
	$(MAKE) -f CMakeFiles/sm64extend.dir/build.make CMakeFiles/sm64extend.dir/sm64extend.c.o
.PHONY : sm64extend.c.o

sm64extend.i: sm64extend.c.i

.PHONY : sm64extend.i

# target to preprocess a source file
sm64extend.c.i:
	$(MAKE) -f CMakeFiles/sm64extend.dir/build.make CMakeFiles/sm64extend.dir/sm64extend.c.i
.PHONY : sm64extend.c.i

sm64extend.s: sm64extend.c.s

.PHONY : sm64extend.s

# target to generate assembly for a file
sm64extend.c.s:
	$(MAKE) -f CMakeFiles/sm64extend.dir/build.make CMakeFiles/sm64extend.dir/sm64extend.c.s
.PHONY : sm64extend.c.s

sm64geo.o: sm64geo.c.o

.PHONY : sm64geo.o

# target to build an object file
sm64geo.c.o:
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/sm64geo.c.o
.PHONY : sm64geo.c.o

sm64geo.i: sm64geo.c.i

.PHONY : sm64geo.i

# target to preprocess a source file
sm64geo.c.i:
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/sm64geo.c.i
.PHONY : sm64geo.c.i

sm64geo.s: sm64geo.c.s

.PHONY : sm64geo.s

# target to generate assembly for a file
sm64geo.c.s:
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/sm64geo.c.s
.PHONY : sm64geo.c.s

sm64walk.o: sm64walk.c.o

.PHONY : sm64walk.o

# target to build an object file
sm64walk.c.o:
	$(MAKE) -f CMakeFiles/sm64walk.dir/build.make CMakeFiles/sm64walk.dir/sm64walk.c.o
.PHONY : sm64walk.c.o

sm64walk.i: sm64walk.c.i

.PHONY : sm64walk.i

# target to preprocess a source file
sm64walk.c.i:
	$(MAKE) -f CMakeFiles/sm64walk.dir/build.make CMakeFiles/sm64walk.dir/sm64walk.c.i
.PHONY : sm64walk.c.i

sm64walk.s: sm64walk.c.s

.PHONY : sm64walk.s

# target to generate assembly for a file
sm64walk.c.s:
	$(MAKE) -f CMakeFiles/sm64walk.dir/build.make CMakeFiles/sm64walk.dir/sm64walk.c.s
.PHONY : sm64walk.c.s

strutils.o: strutils.c.o

.PHONY : strutils.o

# target to build an object file
strutils.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/strutils.c.o
.PHONY : strutils.c.o

strutils.i: strutils.c.i

.PHONY : strutils.i

# target to preprocess a source file
strutils.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/strutils.c.i
.PHONY : strutils.c.i

strutils.s: strutils.c.s

.PHONY : strutils.s

# target to generate assembly for a file
strutils.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/strutils.c.s
.PHONY : strutils.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/utils.c.o
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/utils.c.o
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/utils.c.o
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/utils.c.i
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/utils.c.i
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/utils.c.i
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/utils.c.s
	$(MAKE) -f CMakeFiles/sm64.dir/build.make CMakeFiles/sm64.dir/utils.c.s
	$(MAKE) -f CMakeFiles/f3d.dir/build.make CMakeFiles/f3d.dir/utils.c.s
	$(MAKE) -f CMakeFiles/sm64geo.dir/build.make CMakeFiles/sm64geo.dir/utils.c.s
.PHONY : utils.c.s

yamlconfig.o: yamlconfig.c.o

.PHONY : yamlconfig.o

# target to build an object file
yamlconfig.c.o:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/yamlconfig.c.o
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/yamlconfig.c.o
.PHONY : yamlconfig.c.o

yamlconfig.i: yamlconfig.c.i

.PHONY : yamlconfig.i

# target to preprocess a source file
yamlconfig.c.i:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/yamlconfig.c.i
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/yamlconfig.c.i
.PHONY : yamlconfig.c.i

yamlconfig.s: yamlconfig.c.s

.PHONY : yamlconfig.s

# target to generate assembly for a file
yamlconfig.c.s:
	$(MAKE) -f CMakeFiles/n64split.dir/build.make CMakeFiles/n64split.dir/yamlconfig.c.s
	$(MAKE) -f CMakeFiles/mipsdisasm.dir/build.make CMakeFiles/mipsdisasm.dir/yamlconfig.c.s
.PHONY : yamlconfig.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... n64cksum"
	@echo "... n64split"
	@echo "... mipsdisasm"
	@echo "... edit_cache"
	@echo "... mio0"
	@echo "... sm64extend"
	@echo "... sm64"
	@echo "... sm64walk"
	@echo "... f3d"
	@echo "... sm64compress"
	@echo "... sm64geo"
	@echo "... blast.o"
	@echo "... blast.i"
	@echo "... blast.s"
	@echo "... f3d.o"
	@echo "... f3d.i"
	@echo "... f3d.s"
	@echo "... libmio0.o"
	@echo "... libmio0.i"
	@echo "... libmio0.s"
	@echo "... libsfx.o"
	@echo "... libsfx.i"
	@echo "... libsfx.s"
	@echo "... libsm64.o"
	@echo "... libsm64.i"
	@echo "... libsm64.s"
	@echo "... mipsdisasm.o"
	@echo "... mipsdisasm.i"
	@echo "... mipsdisasm.s"
	@echo "... n64cksum.o"
	@echo "... n64cksum.i"
	@echo "... n64cksum.s"
	@echo "... n64split.o"
	@echo "... n64split.i"
	@echo "... n64split.s"
	@echo "... sm64compress.o"
	@echo "... sm64compress.i"
	@echo "... sm64compress.s"
	@echo "... sm64extend.o"
	@echo "... sm64extend.i"
	@echo "... sm64extend.s"
	@echo "... sm64geo.o"
	@echo "... sm64geo.i"
	@echo "... sm64geo.s"
	@echo "... sm64walk.o"
	@echo "... sm64walk.i"
	@echo "... sm64walk.s"
	@echo "... strutils.o"
	@echo "... strutils.i"
	@echo "... strutils.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... yamlconfig.o"
	@echo "... yamlconfig.i"
	@echo "... yamlconfig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

